### ISSUE TITLE
Signup for new email account

### ISSUE THREAD

**Issue by nobuti** [Zityhub/Onboarding-luisa#1]
Ask @nobuti for an email account. Then set it up with your own settings.

### How to test it

- [x] Go to http://ismyemailworking.com/ and enter your new and shiny email address
- [x] Once you receive the first email, reply
- [x] Wait until the email confirmation arrives
- [x] Open a PR and change your base repo's readme file to include your new email address

**Comment by luisapenalosa** [comment]
Thanks @nobuti for setting this up me 👏
