### ISSUE TITLE
Overview of our GDPR practices

### ISSUE THREAD

**Issue by nobuti** [Zityhub/Onboarding-luisa#14]
You will need to understand our security standards on day one. For that, you have to be familiarised with the concept of GDPR is and how it affects us. 

### How to test it
- [x] Go to https://www.xataka.com/legislacion-y-derechos/gdpr-rgpd-que-es-y-como-va-a-cambiar-internet-la-nueva-ley-de-proteccion-de-datos and read the article
- [x] Also this: https://logsentinel.com/gdpr-practical-guide-developers/
- [x] Update the readme file with the date you read the articles and any thought you have :nail_care:

**Comment by luisapenalosa** [comment]
I've had to read it several times and i still don't understand son much... Does this mean that we have to be able to delete the user data if they ask for it? :S
