### ISSUE TITLE
Tech first meeting

### ISSUE THREAD

**Issue by nobuti** [Zityhub/Onboarding-luisa#5]
This first meeting to go over the 30-day plan together, with emphasis on the agenda of your first week. 

### How to test it
- [x] Take some notes during the meeting
- [x] Create a PR to update the readme with these notes

**Comment by luisapenalosa** [comment]
During the first week, I have defined with Noguerol what my goals are in the first month. Basically start applying the brand to the user app and design the presentations of our product with the new brand
