### ISSUE TITLE
Company first meeting

### ISSUE THREAD

**Issue by nobuti** [Zityhub/Onboarding-luisa#7]
The CEO will talk through the company vision and how we value our culture as much as we value our mission.

### How to test it
- [ ] Create a PR to include in the readme file some details about the meeting.

**Comment by luisapenalosa** [comment]
I´ve been talking about zityhub with Pablo, about my point of view of the company and the reason why I want to join on this project, Also we've talked about the new brand, and how important is prioritize our new website with the new brand to convince our future clients
